// <auto-generated />
namespace MyDeal.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class homePageSlider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(homePageSlider));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181658231_homePageSlider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
